services:

# Uncomment to use OTel or Data Prepper -> OpenSearch pipelines.
#  dataprepper-dev-os:
#    depends_on:
#      - ubi-dev-os
#    container_name: dataprepper
#    image: opensearchproject/data-prepper:2.8.0
#    ports:
#      - 4900:4900
#      - 2021:2021
#    volumes:
#      - ./dataprepper/pipelines.yaml:/usr/share/data-prepper/pipelines/pipelines.yaml
#      - ./dataprepper/data-prepper-config.yaml:/usr/share/data-prepper/config/data-prepper-config.yaml
#    networks:
#      - ubi-dev-os-net

  ubi-dev-os:
    build: ./
    container_name: ubi-dev-os 
    environment:
      discovery.type: single-node
      node.name: opensearch
      plugins.security.disabled: "true"
      logger.level: info
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: SuperSecretPassword_123
      # Requires the Data Prepper container:
      # ubi.dataprepper.url: "http://dataprepper-dev-os:2021/log/ingest"
      # Requires the OTel plugin to be installed.
      #telemetry.feature.tracer.enabled: true
      #telemetry.tracer.enabled: true
      #telemetry.tracer.sampler.probability: 1.0
      #opensearch.experimental.feature.telemetry.enabled: true
      #telemetry.otel.tracer.span.exporter.class: io.opentelemetry.exporter.logging.LoggingSpanExporter
      #telemetry.otel.tracer.exporter.batch_size: 1
      #telemetry.otel.tracer.exporter.max_queue_size: 3
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
      - 9600:9600
    expose:
      - 9200
      - 9600
    networks:
      - ubi-dev-os-net

networks:
  ubi-dev-os-net:
    driver: bridge
